services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  billpay:
    build:
      context: .
      dockerfile: ./apps/billpay/Dockerfile
    ports:
      - "3004:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    ports:
      - "3005:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  subscription:
    build:
      context: .
      dockerfile: ./apps/subscription/Dockerfile
    ports:
      - "3006:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    ports:
      - "3003:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

# Add other microservices similarly...
